### ISSUE TITLE
Issues catch Error nil - Swift 3

### ISSUE THREAD

**Issue by cuongdd** [aws/aws-mobilehub-helper-ios#10]
I have issues this here. Help me, thank a lot :)

![screen shot 2016-10-20 at 3 56 54 pm](https://cloud.githubusercontent.com/assets/9923650/19553390/4b42f86c-96de-11e6-8f70-b12933911bcb.png)

**Comment by rohandubal** [comment]
Hi,
What you should be doing is:

```
if let error = err {
    print(errpr)
}
```

**Comment by cuongdd** [comment]
Thank you. But Error response for function **_AWSCloudLogic.defaultCloudLogic().invokeFunction(LAMBDA_FUNCTION_GET_POSTS_NEWSFEED, withParameters: param) { (result,err) in ... }** _ is not Optional type

![screen shot 2016-10-21 at 9 36 18 am](https://cloud.githubusercontent.com/assets/9923650/19584914/4d78ea3a-9772-11e6-9062-769e97c36df8.png)
And it have issues this here

![screen shot 2016-10-21 at 9 37 49 am](https://cloud.githubusercontent.com/assets/9923650/19584977/c703f6ec-9772-11e6-9ace-9a61f5ce0e86.png)
