### ISSUE TITLE
Issues with function AWSCloudLogic.defaultCloudLogic().invokeFunction  Error is not Optional type - Swift 3

### ISSUE THREAD

**Issue by cuongdd** [aws/aws-mobilehub-helper-ios#12]
Hi, I have the following problem:
Response for function _AWSCloudLogic.defaultCloudLogic().invokeFunction(LAMBDA_FUNCTION_GET_POSTS_NEWSFEED, withParameters: param) { (result,err) in ... } _ is not Optional type

![screen shot 2016-10-21 at 9 36 18 am](https://cloud.githubusercontent.com/assets/9923650/19631600/bcd58b60-99c8-11e6-8d14-a5082062d65d.png)

So it have issues this here
![screen shot 2016-10-21 at 9 37 49 am](https://cloud.githubusercontent.com/assets/9923650/19631610/d3b88c1a-99c8-11e6-92e8-81d8fbe20033.png)

 Can you help me! Thank a lot :)

**Comment by rohandubal** [comment]
Hi, you can mark the return parameters as optionals when you call. 

For e.g.

```
AWSCloudLogic.defaultCloudLogic().invokeFunction(LAMBDA_FUNCTION_GET_NEWS_FEED, withParameters: nil) { (result: AnyObject?, error: NSError?) in
            // handle result and error here
        }
```

Thanks,
Rohan

**Comment by cuongdd** [comment]
@rohandubal  hi, thank you, but script code for you only using Swift 2.2 or Swift 2.3 is OK, i use Swift 3 so error is this : 
![screen shot 2016-10-26 at 10 06 53 am](https://cloud.githubusercontent.com/assets/9923650/19711986/3891aecc-9b64-11e6-90ee-9234f0bccd4f.png)

**Comment by rohandubal** [comment]
For Swift 3, you need to use type `Error` instead of `NSError` for err: parameter in the completion block.

Thanks,
Rohan

**Comment by cuongdd169** [comment]
@rohandubal  thank you, but i think you do not understand the issue

**Comment by BruceBuckland** [comment]
@cuongdd change your code:

**You have**
```
...withParameters: nil) {(result:AnyObject?, err: NSError?
```
**for Swift 3 it should be:**
```
...withParameters: nil) {(result:Any?, err: Error?
```

**Comment by cuongdd169** [comment]
@BruceBuckland, @rohandubal   I understand, I've misunderstood suggested, Thank you very much :)
