### ISSUE TITLE
Facebook and Google providers leave username and imageURL NSUserDefaults set when logged out

### ISSUE THREAD

**Issue by BruceBuckland** [aws/aws-mobilehub-helper-ios#14]
Applies to: AWSFacebookSignInProvider and AWSGoogleSignInProvider.

Is it intentional that the NSUserDefault ProviderKey.userName and Provider.imageURL remain stored on the device even when the user is logged out?  The user might think his "Personally Identifiable Inforomation"  is off the device.

I know this is "public" facebook data.  

But the fact that the user used the device and logged in and out is private, and is PII, and the user might have the reasonable expectation that it would be erased.

**Comment by rohandubal** [comment]
Hi @BruceBuckland ,

Thanks for reporting this issue. No, its not expected that the details will be stored on logout. We will address this issue with next release.

Thanks,
Rohan
