### ISSUE TITLE
AWSIdentityManager. logoutWithCompletionHandler bug

### ISSUE THREAD

**Issue by BruceBuckland** [aws/aws-mobilehub-helper-ios#19]
If you uncheck Enable access to unauthenticated identities in your identity pool.
Then follow this series of calls, you get an error.

1. loginWithSignInProvider with id #1, Facebook user "fred"
2. loginWithSignInProvider with id #2, Google user "ginger"
3. loginWithSignInProvider with "fred" you get the error "GetCredentialsForIdentity keeps failing. Clearing identityId did not help. Please check your Amazon Cognito Identity configuration."  But there is nothing wrong with the configuration, what is wrong is that AWSIdentityManager is mishandling state in loginWithSignInProvider and logoutWithCompletionHandler. Further... 
4. If you look at"User Sign-in" in the sample app, you will show as logged in with the identityId of ginger but facebook picture of fred!
5. Click logout, the app will show you as logged out. If you look at"User Sign-in" in the sample app, you will show as guest with no identityId (because unauthenticated identities are not enabled).
6. Terminate and restart the app and you will be logged in (without entering an Id.) This is because the session for Google is still active (in NSUserDefaults) and is restored.  If you look at"User Sign-in" in the sample app, you will show as logged in with the identityId of ginger and with her picture too (correct).

Alternatively, if you CHECK Enable access to unauthenticated identities in your identity pool. You get similar errors and problems.

I have submitted a pull request to resolve these issues.

**Comment by rohandubal** [comment]
Hi @BruceBuckland ,

Currently, the Identity Manager is designed to handle only one active Sign In provider at any given time. The Identity Manager does not expect two sign in providers signed in at the same time as there is no merging of identities available. Mobile Hub does not have merging of identities. Every sign-in using different sign-in provider is a different user / identity. This is what is demonstrated in the Sample App downloaded from Mobile Hub. I will go through the PR you have submitted and discuss with the team if we can merge that request. Thank you for submitting the PR. Resolving this issue and will follow up on the PR.

Thanks,
Rohan
