### ISSUE TITLE
Register for remote push notifications with categories

### ISSUE THREAD

**Issue by Yanivox** [aws/aws-mobilehub-helper-ios#2]
Hi, It will be nice if the AWSPushManager will register to push notification with Custom categories.
I implemented it by myself in the following solution.

`
static NSSet<UIUserNotificationCategory *> \* _pushCategories = nil;
- (void)registerPushNotificationCategories:(NSSet<UIUserNotificationCategory *> *)categories {
  
  _pushCategories = categories;
  }
- (void)registerForPushNotifications {
  UIApplication *application = [UIApplication sharedApplication];
  UIUserNotificationType types = UIUserNotificationTypeBadge | UIUserNotificationTypeSound | UIUserNotificationTypeAlert;
  UIUserNotificationSettings *notificationSettings = [UIUserNotificationSettings settingsForTypes:types
                                                                                       categories:_pushCategories];
  [application registerUserNotificationSettings:notificationSettings];
  [application registerForRemoteNotifications];
  }

`

because that the resigerForPushNotifications called when class created I added it as a static property.

Thanks

**Comment by muellerfr** [comment]
Hello @Yanivox 

We will be retiring this repo soon as the AWS iOS SDK provides push notification support via Pinpoint. Any future issues/feature requests regarding aws-mobilehub-helper should be posted at aws-sdk-ios/issues.
