### ISSUE TITLE
Please Push the new version of aws-mobilehub-helper-ios

### ISSUE THREAD

**Issue by BruceBuckland** [aws/aws-mobilehub-helper-ios#20]
The new version of this repo in use on the AWS Mobile Hub has many desirable features.  

- The AWSIdentityManagerFactory establishes (at last) a way to connect additional AWSSignInProviders (IdP's) to the AWSIdentityManager so that sessions will be restarted upon starting the app.

- An AWSSignInProvider was added for Cognito (Your) User Pools.  

While we created custom code to do these things, we would like to maintain compatibility with your (excellent) helper going forward, but we cannot integrate because we don't have access to the code.

I know @rohandubal mentioned that the new code will be pushed very soon.  But would it be possible to push the development branch, to to make very soon ... sooner?

Thanks

**Comment by FlorianMielke** [comment]
Totally agree. It would be very helpful to keep both repositories in sync.

**Comment by BruceBuckland** [comment]
thank you!
