### ISSUE TITLE
getDetails does not execute it's callback with facebook as signin provider

### ISSUE THREAD

**Issue by hhartz** [aws/aws-mobilehub-helper-ios#24]
I'm using `AWSMobileHubHelper`, and sign in + fetch attributes using

    let signInProvider = AWSFacebookSignInProvider.sharedInstance()
    signInProvider.setPermissions(["email", "public_profile"])
    let identityManager = AWSIdentityManager.defaultIdentityManager()
    identityManager.loginWithSign(signInProvider, completionHandler: { (result, error) in
        self.user = self.pool.currentUser()
        self.user.getDetails().continue({ task in
            ...
        })
    })

In the completion handler, using a traditional username/password I do get details (and attributes) back - while using AWSFacebookSignInProvider the handler is not executed.

**Comment by BruceBuckland** [comment]
Do you get to log in on Facebook?  Does it ask for your password or permission?  Or are you just hitting "done" or "Cancel".  Because AWSFacebookSignInProvider has a bug where it does nothing (not even the completion handler) if the user cancels signin.  This is in a pull request on this repo, and they have said they will accept it.

**Comment by hhartz** [comment]
I can log in fine, the issue is setting/getting user attributes from cognito after authorization

**Comment by BruceBuckland** [comment]
Um ... cognito user pools has attributes, cognito identity does not. You have to be logged in as a cognito user pools users to update attributes.   Of course with the right permissions you could update attributes in Facebook maybe , but all the examples ask for read permissions and I have not tried updating facebook

**Comment by minbi** [comment]
[Pull request#16](https://github.com/aws/aws-mobilehub-helper-ios/pull/16) was merged. If this problem still occurs, feel free to re-open
