### ISSUE TITLE
Cognito Question: Custom user attributes

### ISSUE THREAD

**Issue by golfguy0082** [aws/aws-mobilehub-helper-ios#25]
Is there a way to retrieve custom attributes about a user (i.e. email address)?

**Comment by mlshon** [comment]
Hi,
Currently, there isn't a way to do so.
We will take this as a feature request and update this thread accordingly.

**Comment by muellerfr** [comment]
Hello @golfguy0082 

We will be retiring this repo soon as the AWS iOS SDK provides authentication support. Any future issues/feature requests should be posted at aws-sdk-ios/issues.
