### ISSUE TITLE
AWSSignInProvider question. Is a "Developer Authenticated SignIn" provider in roadmap?

### ISSUE THREAD

**Issue by monday8am** [aws/aws-mobilehub-helper-ios#26]
Now we have providers for Facebook, Google, UserPool etc. but a AWSSignInProvider to deal with "developer authenticated identities" is missing. 
Is it in your plans? 
In case of not, could you provide some hints of how to implement it?

**Comment by rohandubal** [comment]
Hi,

The Mobile Hub Helper supports integration with developer authenticated identities. To achieve it,  you can refer to the user pools example: https://github.com/aws/aws-mobilehub-helper-ios/blob/master/AWSMobileHubHelper/SignIn/AWSCognitoUserPoolsSignInProvider.h 
where it adopts the `AWSSignInProvider` protocol.

You also need to use `AWSSignInProviderFactory` from AWSMobileClient to make sure the sign in provider you implemented is registered.

Thanks,
Rohan

**Comment by monday8am** [comment]
thanks @rohandubal

**Comment by monday8am** [comment]
referring to this issue, just a couple of comments to improve the thread a bit. I managed to created a custom `AWSSignInProvider` implementation to use "developer authenticated identities" but with the follow hacks:
- I implemented `AWSSignInProvider` following the UserPool case as you suggest me.

- I made the method [completeLogin](https://github.com/aws/aws-mobilehub-helper-ios/blob/master/AWSMobileHubHelper/Identity/AWSIdentityManager.m#L154) public, cos I´m using MobileHub from Swift.

- I needed to manage identities-tokens-logins in a custom way. For that reason, I created a `AWSCognitoCredentialsProviderHelper`, then a `AWSCognitoCredentialsProvider` using it and then I passed it to the `AWSSignInProvider`. It is like a kind of mix between objects that have the same purpose but for some cases, you need the control of your credential provider.

The implementation is working correctly but if a better (elegant) solution is possible please, just let me know :)
