### ISSUE TITLE
Needs to be updated for Swift 3

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-mobilehub-helper-ios#27]
I get various weird errors after trying to update this for Swift 3, would be easier if it's just set up with Swift 3 form the start as it's been out for months now.

Thanks.

**Comment by mboiman** [comment]
I am waiting for it too. Amazon, does not answering or saying when this feature will be done :(

**Comment by plm75** [comment]
Swift 3 has been out for more than 6 months now 😞 
Has somebody from AWS even acknowledged this issue ?

**Comment by azsolinsky** [comment]
You can rest assured that we know this is a high priority for customers and are working on adding support.

**Comment by minbi** [comment]
Swift 3 support has just been released, please download the MobileHub sample app again. Checking that it was generated with v0.10 template shown in any file's comments at the top.

**Comment by therobwatson** [comment]
For that template, the AWS Mobile Hub Client AWSConfiguration.swift seems to have a typo?

```
#if RELEASE
let ServiceKey: String = "Prod";
#else
let ServiceKey: String = "Devo";
#endif
```

Should it be "Dev", not "Devo"?
