### ISSUE TITLE
Crash in -[AWSIdentityManager completeLogin]

### ISSUE THREAD

**Issue by virt87** [aws/aws-mobilehub-helper-ios#28]
After the update to 2.5.0, the app is constantly crashing with the following error
```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AWSTask exception]: unrecognized selector sent to instance 0x608001261280'
```

**Comment by minbi** [comment]
Hi virt87,

The AWSMobileHubHelper does not support SDK version 2.5.0 at this time. I will update this thread when it is ready.

**Comment by MichealSBingham** [comment]
Is it ready yet?
