### ISSUE TITLE
How do I install MobileHubHelper framework?

### ISSUE THREAD

**Issue by MichealSBingham** [aws/aws-mobilehub-helper-ios#30]
Currently, I integrated the mobile hub helper framework from the AWS Mobile Hub Helper console; however, it is currently not updated to Swift 3 and the 2.5.0 version but this one here is recently updated; however, I am unsure of how to install this. Can someone help me?

**Comment by SalehAlDhobaie** [comment]
I was fixing this issue by adding all dependency from Cococapods and I add MobileHubHelper manually or by using Carthage.

**Comment by MichealSBingham** [comment]
Having cocoapod support would help tremendously. I wasn't aware that you could install MobileHubHelper with Carthage (doing it manually can be a pain). Are there instructions by instally it with Carthage?

**Comment by DanGreenMH** [comment]
We've updated the Swift framework in the AWS Mobile Hub Helper console to include Swift 3 support. You should be able to download the latest from there.
