### ISSUE TITLE
support Push Notification in iOS 10 

### ISSUE THREAD

**Issue by SalehAlDhobaie** [aws/aws-mobilehub-helper-ios#31]
Hi all, 
I just find out there is an issue with Sound in iOS 10 while I was using AWS SNS + MobileHubHelper. 
I solve by adding these line of code.

`extension AWSPushManager {
    
    @objc func registerForPushNotifications10() {
        
        if #available(iOS 10.0, *) {
            let center = UNUserNotificationCenter.current()
            center.requestAuthorization(options:[.badge, .alert, .sound]) { (granted, error) in
                // Enable or disable features based on authorization.
                if error == nil {
                    print("\n\n\n\n\n\n\n\n\n \(#function), \(#line) value: \(granted)")

                }else {
                    print(error!)
                }
            }
        } else {
            self.registerForPushNotifications()
            // Fallback on earlier versions
        }
    }
    
    
}
`

I add It as extension with bridge function as ObjC since I'm using Swift in my application. and it's easy to be convert to Objc.

**Comment by muellerfr** [comment]
Hello @SalehAlDhobaie 

We will be retiring this repo soon as the AWS iOS SDK provides push notification support via Pinpoint. Any future issues/feature requests regarding aws-mobilehub-helper should be posted at aws-sdk-ios/issues.
