### ISSUE TITLE
Update code to last version used in Mobile Hub console.

### ISSUE THREAD

**Issue by monday8am** [aws/aws-mobilehub-helper-ios#34]
Could you please update this repo (or create a new branch) with the code used when you download the sample app from the console? For example, the **AWSSignInManager** is totally missing in this repo, the names and protocols have changed, etc.

**Comment by rohandubal** [comment]
The latest source is now available.

Thanks,
Rohan

**Comment by monday8am** [comment]
Thanks a lot @rohandubal!
