### ISSUE TITLE
[Request] KVO compatibility 

### ISSUE THREAD

**Issue by plm75** [aws/aws-mobilehub-helper-ios#35]
Hello,

For the moment, unless I'm mistaken, it looks like none of the helpers are KVO compatible (i.e. it is not possible to dynamically observe properties).

For instance,  in the Swift generated code, `AWSSignInManager.sharedInstance().isLoggedIn` or `AWSUserFileManager.defaultUserFileManager().uploadingContents` are not marked `dynamic` 

It would be great if we could have KVO compatibility because that would allow, among other things, to use these helpers in conjunction with a reactive library (RxSwift).

Thanks

**Comment by wdane** [comment]
Thanks plm,

We'll take this request into consideration when prioritizing our work. As always direct customer feedback such as this is a great way to help drive and prioritize our development.!
