### ISSUE TITLE
 Failed to load Info.plist from bundle at path

### ISSUE THREAD

**Issue by Knowledge91** [aws/aws-mobilehub-helper-ios#38]
When I add _AWSMobileHubHelper.framework_ into `Embedded Binaries` i get the error 

>  Failed to load Info.plist from bundle at path...

Following the a forum entry from a year ago: [Forum AWS](https://forums.aws.amazon.com/thread.jspa?messageID=712736), the bug is solved by removing _AWSMobileHubHelper.framework_ from `Embedded Binaries` and adding it **ONLY** to the `Linked Frameworks and Libraries`. 

Could you please fix this or clear the confusion in the README.md. I took me two days two figure out what is causing my .plist problem and was lucky enough to encounter the above mentioned forum entry.

**Comment by mlshon** [comment]
Sorry that you had to go through that. We will work on updating the README to make that clear!

**Comment by kvasukib** [comment]
We have added the instructions to README.md. Thanks, @Knowledge91 for pointing it out.
