### ISSUE TITLE
AWSUserFileManager using a key i get a "Ambiguous use of init(forKey:)" error.

### ISSUE THREAD

**Issue by Beyondlost** [aws/aws-mobilehub-helper-ios#39]
Hi,
  When i try to init the AWSUserFileManager using a key i get a "Ambiguous use of init(forKey:)" error.

This is the simple code causing the error, which is straight from the framework header so i don't think its me.

let userFileManager = AWSUserFileManager(forKey: "mybucketconfigkey")

I am using the default config in the info.plst file and works fine, but i have a one off instance where i need to change the bucket and can't seem too without doing this. 

I am using the framework downloaded from the MobileHub in the last 2 weeks with Swift 3 IOS 10.3

Thanks!

**Comment by mlshon** [comment]
Thanks for letting us know! For now, are you able to just use the default userfilemanager and change the configuration in the info.plist?

We will work on a fix.

**Comment by shawnn72** [comment]
Did this get resolved?  I ran into this issue as well.  I need to support multiple buckets in my application and this is the only way to support it as far as I can tell.

**Comment by kvasukib** [comment]
Hi @Beyondlost and @shawnn72,

You can see the constructor of UserFileManager here: https://github.com/aws/aws-mobilehub-helper-ios/blob/master/AWSMobileHubHelper/UserFiles/AWSUserFileManager.m#L80,L111

The constructor fetches the bucket name and creates an object based on that. Until we fix the bug, you can write the code that can create an instance of UserFileManager based on bucket name you supply.

`
NSString *bucketName = "Your_Custom_S3_Bucket_Name";
if (bucketName) {
            _defaultUserFileManager = [[AWSUserFileManager alloc] initWithType:AWSContentManagerTypeS3
                                                                        bucket:bucketName
                                                                 cloudFrontURL:nil
                                                          serviceConfiguration:serviceConfiguration
                                                                    identifier:AWSInfoDefault];
} 
`

We will fix the bug in one of the future releases.

**Comment by Beyondlost** [comment]
Hi kvasukib,
    I'm working in swift and i don't see AWSUserFileManager(initWithType: exposed to use in AWSUserFileManager.h?  Also don't see the AWSContentManagerTypeS3 constant. Do i need to import something more than the AWSMobileHubHelper to the file?

Thanks,
   Jason H

**Comment by rohandubal** [comment]
Hello,

The MobileHubHelper library is not supported anymore and UserFileManager is to be replaced with S3TransferUtility client. You can find the instructions to usage here: 
https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-user-data-storage.html

Thanks,
Rohan
