### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by plm75** [aws/aws-mobilehub-helper-ios#40]
Adding a Unit Test target to the sample application or a custom application doesn't work.

Could you please provide more information/guidance as to how to integrate unit tests ?

Thanks

**Comment by rohandubal** [comment]
Could you elaborate more on this usecase? For which part do you want to add unit tests?

**Comment by plm75** [comment]
Hello @rohandubal ,
What I'm trying to do is just be able to create and run unit tests on an application that integrates mobile hub helper.

Steps to reproduce issue:
A) With sample application
- download sample application from mobile hub site
- in xcode, add a new iOS Unit Test target to the project
-> Xcode complains about: 'AWSAPIGateway/AWSAPIGateway.h not found' and 'failed to import bridging header'

I checked the the unit test target build settings and the bridging header is there (same as for the application)

B) With a custom application:
- download sdk from mobile hub site and follow instructions to integrate inside application.
- check that application works fine and interacts correctly with AWS resources
- add a new iOS Unit Test target to the project
- add `@testable import [appname]` to the top of a test file
-> Xcode complains about: "Apple Mach-O Linker Error - Linker command failed with exit code 1 (user -v to see invocation)"

For case A: if I go I the build settings for the test target and DELETE the Bridging Header from the Swift compiler options, I get the same error as in case B

**Comment by minbi** [comment]
For scenario A, can you go to `Build Settings` search for `Bridging Header`. Look at the left-hand navigation and choose your `somethingTests` under `Targets` and make sure that `'AWSAPIGateway/AWSAPIGateway.h` is specified in the `Objective-C Bridging Header field.

**Comment by plm75** [comment]
![screen shot 2017-06-16 at 08 19 36](https://user-images.githubusercontent.com/18553600/27214458-e3620fa8-526c-11e7-9ad0-ab7e3e7432e6.png)

@minbi : there already is a bridging header that was automatically added by Xcode.
The file contains: 
#import "AWSAPI_XXXXX_XXXXX_aaa.h"
#import "AWSAPI_XXXXX_XXXXX_bbb.h"

**Comment by muellerfr** [comment]
This issue has been closed because it has not had recent activity. Any future issues regarding aws-mobilehub-helper should be posted at aws-sdk-ios/issues.
