### ISSUE TITLE
isLoggedIn vs isSignedIn ?

### ISSUE THREAD

**Issue by plm75** [aws/aws-mobilehub-helper-ios#41]
The code comments state:

- AWSCognitoIdentityUser - isSignedIn: "determines whether this user has an active session or not"
- AWSSignInManager - isLoggedIn: "Indicates whether the user is signed-in or not"

Could you please provide more details on the two properties ? Do they essentially reflect the same state on the user object and then are they always in sync or do they reflect different states on the user and then what are the differences and how do they relate ?

I just want to know if I need to show a login screen to the user.  Which property should I check ?

Thanks

**Comment by minbi** [comment]
When you are using user pools, `isLoggedIn` will be the same as `isSignedIn`. Otherwise it represents that the user is logged into Facebook, Google, etc.

**Comment by plm75** [comment]
@minbi : thanks
