### ISSUE TITLE
GenerateHelperFramework.sh script fails. Please fix.

### ISSUE THREAD

**Issue by jukka-palomaki** [aws/aws-mobilehub-helper-ios#43]
If I do e.g.

pod install
./Scripts/GenerateHelperFramework.sh AWSFacebookSignIn

-> it fails. See below. I have tried to follow the instructions accurately. Could you please fix this? 

** BUILD FAILED **
 
 
The following build commands failed:
                CompileC /Users/jukkpalo/Library/Developer/Xcode/DerivedData/AWSMobileHubHelper-hayatotsxrkdpqbplxpqqumfeghb/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/AWSCore.build/Objects-normal/i386/AWSDDOSLogger.o AWSCore/AWSCore/Logging/AWSDDOSLogger.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error occurred, abort

**Comment by jukka-palomaki** [comment]
I would also like to know if this version of AWSMobileHubHelper works with latest AWS Libraries 2.6.10?

**Comment by kredden** [comment]
What are you trying to do?  A lot of the MobileHub helper code was move into the SDK.  If you are trying to add a FaceBook button, check out these updated docs and try the latest SDK:

http://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-user-sign-in.html#set-up-email-and-password

Regards,
Kevin

**Comment by jukka-palomaki** [comment]
I am just trying to upgrade AWS libraries and AWSMobileHubHelper codes to latest version in our app. We have three login methods there (UserPools, Facebook, Google).

**Comment by jukka-palomaki** [comment]
It looks like AWSIdentityManager is not in the SDK anyway. That is what we need.

**Comment by kredden** [comment]
Yes, that should help.  It will be a little bit of work but shouldn't be too much.  As I mentioned above, the login code is now built in to the SDK so you don't need the helper code for that anymore.  If you look through the link I provided above it should also help in the migration.

**Comment by kredden** [comment]
Please reopen this issue if the above information does not answer your questions.

Regards,
Kevin
