### ISSUE TITLE
AWSMobileHelper build issues

### ISSUE THREAD

**Issue by nadein** [aws/aws-mobilehub-helper-ios#44]
### 1) Building with Xcode
While building with Xcode I have experienced next issue:
In AWSCore (v2.5.0) class `AWSDDOSLogger` I have a build time error
Static_assert failed "format argument must be a string constant" in lines containing  `os_log_info`

```
switch (logMessage->_flag) {
            case AWSDDLogFlagError     :
                os_log_error(OS_LOG_DEFAULT, msg);
                break;
            case AWSDDLogFlagWarning   :
            case AWSDDLogFlagInfo      :
                os_log_info(OS_LOG_DEFAULT, msg);
                break;
            case AWSDDLogFlagDebug     :
            case AWSDDLogFlagVerbose   :
            default                 :
                os_log_debug(OS_LOG_DEFAULT, msg);
                break;
        }
```

So in order to build I have to comment this lines.
Also please update this lib to support latest AWS-SDK-iOS dependency.

### 2) Building with script
While running `GenerateHelperFramework.sh` (as mentioned in README) 

`sh GenerateHelperFramework.sh AWSMobileHubHelper`

I got an error:

```
Framework: Cleaning framework...
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
Error occurred, abort
```

**Comment by kvasukib** [comment]
Thank you @nadein for reporting to us. 

1) Building with Xcode: We will update the Podifle to download the latest dependencies
2) Building with script: I was not able to reproduce this error. Can you give more details of this? Can you try doing a `pod install` and then do `sh GenerateHelperFramework.sh AWSMobileHubHelper`?

**Comment by muellerfr** [comment]
This issue has been closed because it has not had recent activity. Any future issues regarding aws-mobilehub-helper should be posted at aws-sdk-ios/issues.
