### ISSUE TITLE
AWSUserFileManager.default() Swift 3 issue

### ISSUE THREAD

**Issue by danieldelouya** [aws/aws-mobilehub-helper-ios#6]
Hi
Xcode tells me AWSUserFileManager.defaultUserFileManager() has been renamed to AWSUserFileManager.default(), but when I set it to that, it gives me an error and says: "Ambiguous use of 'default()'"

What's going on? How can I properly initialize it in Swift 3, so I know it links up with the S3 id in info.plist? 

I've tried:

manager = AWSUserFileManager()
manager = AWSUserFileManager.self()
manager = AWSUserFileManager.init()
manager = AWSUserFileManager.UserFileManager(forKey: "xxxxxx")

None seem to work.

**Comment by georgel** [comment]
Love to get an answer on this also :)

**Comment by achud** [comment]
This issue has been resolved in the latest revision of the AWS Mobile Hub Helper framework. You can download the latest revision from the AWS Mobile Hub console. Git Hub has not yet been updated with the latest. It will be updated shortly.

Sincerely,
Andrew C
AWS Mobile Developer Experience

**Comment by danieldelouya** [comment]
Thank you! @achud 
Btw. ETA on Mobile Hub in Swift 3?

**Comment by achud** [comment]
We're aware of the issue and have had multiple requests for supporting Swift 3 without the legacy compiler setting. We're working on prioritizing the required changes in AWS Mobile Hub. Sorry, I can't provide an expected date at this time.

**Comment by rohandubal** [comment]
The above issue is resolved with this commit:
https://github.com/aws/aws-mobilehub-helper-ios/commit/2c5b40ab2f36e381d4961f7f5cabc55147b3806f

All the clients should be now usable without any issues on both Swift 2 and Swift 3 by using `.defaultXXX()` when the configuration is present in `info.plist`

E.g. `AWSUserFileManager.defaultUserFileManager()` for the User File Manager.

**Comment by danieldelouya** [comment]
@achud Ok no worries. At least the Mobile Hub Helper framework is fully functional now. Thanks again!
