### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by tfonfara** [aws/aws-mobilehub-helper-ios#7]
Hi there,

are there any plans to distribute the MobileHub Helper via Cocoapods same as the other AWS libraries?

Thanks!

**Comment by azsolinsky** [comment]
Hi tfonfara,

Thank you for your feedback. We will consider your question as a Feature Request for Cocoapods support and will update you when appropriate.

Best Regards,
Jeff S
Amazon SDE

**Comment by pantuspavel** [comment]
Any update on this request?

**Comment by sridharrajagopal** [comment]
Any update? 

Thanks,
Sridhar

**Comment by ojacevedo** [comment]
Need better support with this request and Swift 3.  Google Firebase looks like a good substitute for now.

**Comment by MichealSBingham** [comment]
Will there be cocapods support?

**Comment by XBeg9** [comment]
Any updates?

**Comment by achud** [comment]
We do not currently have any plans to distribute the Mobile Hub helper framework via CocoaPods, but the product management team is aware of the request. However, you can download the framework from the AWS Mobile Hub console on the "Integrate" page and you can get it from git hub here...

https://github.com/aws/aws-mobilehub-helper-ios

Sincerely,
Andrew C
AWS Mobile Developer Experience

**Comment by kvasukib** [comment]
Hello,

Sorry for the inconvenience caused.

Most parts of the Hub Helper has been made as an SDK component and are available through Cocodpods.

pod 'AWSAuth/Core'
pod 'AWSAuth/UserPoolsSignIn'
pod 'AWSAuth/GoogleSignIn'
pod 'AWSAuth/FacebookSignIn'
pod 'AWSAuth/UI'

Thanks
