### ISSUE TITLE
conflict with -ObjC requirement for PayPal

### ISSUE THREAD

**Issue by panlong90** [aws/aws-mobilehub-helper-ios#8]
Maybe this is not the right venue. But I've been struggling with this issue for a while. With PayPal SDK, a -ObjC tag is required for the Other Linker Flag section in the Building Settings. However, with this tag, I keep getting compiler errors. Any suggestion how I can solve this issue?

**Comment by fernandolicon** [comment]
I'm running with the same error but with GoogleAnalytics pod, seems like the only way to solve it is removing the -ObjC, but this conflicts with GA. If you find a solution let me know.

**Comment by panlong90** [comment]
The compiling errors went away after I added AWSSNS framework as embedded framework (which I don't need for any other reasons). In my case, the errors seemed all point to a couple of header files in the mobilehubhelper  that implies/refers to that framework. Hope that helps. 
I would still consider it a bug though.

**Comment by rohandubal** [comment]
Hi, you could use the -force_load flag as an alternative to the -ObjC flag. 
An example usage is: 
`-force_load $(PROJECT_DIR)/<<SDK_PARENT_PATH>>/FrameworkRequiringObjC.framework`

Thanks,
Rohan

**Comment by panlong90** [comment]
Thanks! Will give it a try. Any suggestion on how to do this with Cocoapods? Just manually change it to force load after installed with pod?

**Comment by eliot1019** [comment]
Hi @panlong90, could you let me know if you figured out this issue?

**Comment by panlong90** [comment]
Sorry my memory about this issue is getting blurry. The only recollection that I'm certain is that it took me a long time to find a work around. I think in my case I stopped using AWS Mobile Helper Class and opted to use AWS Cognito directly which made the issue go away. Also, I stopped using Pods for AWS stuff.

**Comment by fernandolicon** [comment]
Same here, I needed to stop using AWS with Pods and also I removed the conflicting Pod (in my case it was GoogleMaps) and added it as a Framework.

I also needed to make some changes on the Podfile, I posted what I did on the Podfile here http://stackoverflow.com/questions/31410731/remove-objc-flag-from-cocoapods-install/40014816#40014816

**Comment by eliot1019** [comment]
Hi guys, I figured out how to solve this issue and still use AWS Mobile Helper. I successfully installed Firebase Analytics(which are static libraries) + other google frameworks and everything is going well. Let me know if you are still interested in a solution.

**Comment by panlong90** [comment]
That's great! @eliot1019 Do you mind sharing what you did? Thanks!

**Comment by eliot1019** [comment]
Like one of the prev comments mentioned, I did -force_load, however my path went one folder deeper past the .framework. I also included the name of the file inside the .framework path using finder. Hope this helps.
-force_load $(PROJECT_DIR)/FrameworkRequiringObjC.framework/framework

**Comment by jplongo** [comment]
Can you give me more information about adding `-force_load` on Xcode.
I'm have the same issue when using GVRSDK on my project. I'm using libraries files *.a not *.framework. 
I've tried to add this to my library declaration but no way. Does this flag work with library ? I've not found any info about it.
